### ISSUE TITLE
ChatLLaMA-zh-7B-int4模型加载报错问题

### ISSUE THREAD

**Issue by binzhouchn** [ydli-ai/Chinese-ChatLLaMA#12]
替换成int4模型后加载会报如下错误，请帮忙看下
Traceback (most recent call last):
  File "scripts/generate_chatllama.py", line 86, in <module>
    model = load_model(model, args.load_model_path)
  File "/workspace/TencentPretrain/tencentpretrain/model_loader.py", line 11, in load_model
    model.load_state_dict(torch.load(model_path, map_location="cpu"), strict=False)
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)

**Comment by Daniel-1997** [comment]
我也遇到了和你类似的问题，就是将7b替换成int4的时候，运行generate_chatllama 时候出错
`Traceback (most recent call last):
  File "E:/bert-multi-lables/liujinming/chinese_llama/TencentPretrain/scripts/generate_chatllama.py", line 86, in <module>
    model = load_model(model, args.load_model_path)
  File "E:\bert-multi-lables\liujinming\chinese_llama\TencentPretrain\tencentpretrain\model_loader.py", line 11, in load_model
    model.load_state_dict(torch.load(model_path, map_location="cpu"), strict=False)
  File "E:\fengchen\Chinese-Text-Classification-Pytorch\venv\lib\site-packages\torch\serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "E:\fengchen\Chinese-Text-Classification-Pytorch\venv\lib\site-packages\torch\serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: could not find MARK`

**Comment by chenhuixi1** [comment]
同样有这个问题

**Comment by ydli-ai** [comment]
int4模型只能在llama.cpp用
________________________________
发件人: chenhuixi1 ***@***.***>
发送时间: Tuesday, April 4, 2023 7:27:03 PM
收件人: ydli-ai/Chinese-ChatLLaMA ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [ydli-ai/Chinese-ChatLLaMA] ChatLLaMA-zh-7B-int4模型加载报错问题 (Issue #12)


同样有这个问题

―
