### ISSUE TITLE
运行脚本generate_chatllama.py后，tokenizer报错

### ISSUE THREAD

**Issue by tianmala** [ydli-ai/Chinese-ChatLLaMA#8]
Traceback (most recent call last):
  File "scripts/generate_chatllama.py", line 82, in <module>
    args.tokenizer = str2tokenizer[args.tokenizer](args)
  File "/home/mo/llama/TencentPretrain/tencentpretrain/utils/tokenizers.py", line 255, in __init__
    super().__init__(args, is_src)
  File "/home/mo/llama/TencentPretrain/tencentpretrain/utils/tokenizers.py", line 30, in __init__
    self.sp_model.Load(spm_model_path)
  File "/home/mo/miniconda3/envs/llm_env/lib/python3.8/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/home/mo/miniconda3/envs/llm_env/lib/python3.8/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())] 

我运行脚本后报错了，请问这个问题有谁遇到过嘛

**Comment by davikl** [comment]
我也是求教

**Comment by rayguo01** [comment]
同样出错

**Comment by GuanLinZhang** [comment]
subscribe this issue as meet the same issue

**Comment by lylcst** [comment]
同样问题，怎么解决

**Comment by 2775919186** [comment]
spm_model_file = '../ChatLLaMA-zh-7B/tokenizer.model'这个分词模型是不是损坏了？

**Comment by Data2Me** [comment]
同样出错

**Comment by Data2Me** [comment]
> > > spm_model_file = '../ChatLLaMA-zh-7B/tokenizer.model'这个分词模型是不是损坏了？
> > 
> > 
> > 我测试了没有遇到这个问题，检查一下Sentencepiece版本？ 我这里是0.1.97
> 
> 我这边Sentencepiece版本也是0.1.97，刚试了还是报错： File "/opt/conda/lib/python3.10/site-packages/sentencepiece/**init**.py", line 310, in LoadFromFile return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg) RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())]

已解决，重新下载模型权重文件。git clone时要安装git lfs

**Comment by YYForReal** [comment]
> > > > spm_model_file = '../ChatLLaMA-zh-7B/tokenizer.model'这个分词模型是不是损坏了？
> > > 
> > > 
> > > 我测试了没有遇到这个问题，检查一下Sentencepiece版本？ 我这里是0.1.97
> > 
> > 
> > 我这边Sentencepiece版本也是0.1.97，刚试了还是报错： File "/opt/conda/lib/python3.10/site-packages/sentencepiece/**init**.py", line 310, in LoadFromFile return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg) RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())]
> 
> 已解决，重新下载模型权重文件。git clone时要安装git lfs

安装之后下载模型权重文件速度太慢了，有什么好方法吗？
